### creating an endpoint for addind pizza
POST http://localhost:3000/pizzas
Content-Type: application/json

{
    "name": "Pizza Bianca",
    "price": 5
}

### endpiont for listing all pizzas
GET http://localhost:3000/api/pizzas
Content-Type: application/json

###  Endpoint for deleting a pizza by ID
DELETE http://localhost:3000/pizzas/1
Content-Type: application/json

### endpoint for ordering pizza
POST http://localhost:3000/order
Content-Type: application/json

### Endpoint for adding an item to an existing order
POST http://localhost:3000/order/8/items
Content-Type: application/json

{
    "pizza_id": "2",
    "quantity": 5
}
